
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "./milkv-duos.json"

rustflags = [
    "-Clink-args=-Tbl.ld",
    "-C", "linker-flavor=gcc",
]

[target.milkv-duos]
linker = "riscv64-none-elf-gcc"