[package]
name = "bl"
version = "0.1.0"
edition = "2021"


[dependencies]
milkv-rs = { path = "../milkv-rs", features = ["ddr"]}
embedded-graphics = "*"

[profile.release]
panic = "abort"
opt-level = "z"
lto = "fat"
codegen-units = 1

[profile.dev]
panic = "abort"
