[package]
name = "bl"
version = "0.1.0"
edition = "2021"


[dependencies]
cfmt = {version = "0.*", package = "const_format"}

[profile.release]
panic = "abort"
opt-level = "s"
# lto = "fat"

[profile.dev]
panic = "abort"
